<?php

use Drupal\Component\Utility\Html;
use Drupal\Component\Serialization\Json;
use Drupal\Component\Utility\DeprecationHelper;
use Drupal\Core\Utility\Error;
/**
 * @file
 * asu_user.module - ASU User code.
 *
 * @author
 * Dan Poenaru <dan.poenaru@deptagency.com>
 *
 * Module provides customization functions for the users. Some code is from the
 * asu_userpicker made by Michael Samuelson.
 *
 */
/**
 * API function to get a person/profile record from Elastic.
 *
 * @param string|int $asurite An ASURITE.
 *
 * @return array Elastic record for profile.
 */
function _asu_user_get_elastic_profile_record($asurite) {

  // Abort.
  if (is_null($asurite)) {
    return;
  }

  // Do Elastic query ala https://search.asu.edu/api/v1/webdir-profiles/faculty-staff/filtered?asurite_ids=myasurite
  // And populate $record.
  $elastic_base_url = \Drupal::config('asu_user.settings')->get('asu_user_elastic_query_url');
  $elastic_query_url = $elastic_base_url . '?asurite_ids=' . Html::escape($asurite);

  $client = \Drupal::httpClient();
  try {
    $response = $client->get($elastic_query_url);
    $data = $response->getBody()->getContents();

    $elastic_data = Json::decode($data);

    // Check here that the asurite ID is a 100% match with the record, as
    // Elastic does a "contains" match.
    $record = NULL;
    $elastic_count = $elastic_data['meta']['page']['total_results'];
    if ($elastic_count > 0) {
      foreach ($elastic_data['results'] as $result) {
        if ($result['asurite_id']['raw'] == $asurite) {
          $record = $result;
        }
      }
    }
    return $record; // Should only be one.
  }
  catch (Exception $e) {
    Error::logException(\Drupal::logger('asu_user'), $e);
  }
  return [];
}
