<?php

use Drupal\Core\Url;

/**
 * Implements hook_preprocess_HOOK().
 */
function asu_news_preprocess_block(&$variables) {
  $plugin_id = $variables['base_plugin_id'] ?? '';

  if ($plugin_id != 'inline_block') {
    return;
  }

  if ($variables['derivative_plugin_id'] == 'news') {
    $rand_id = random_int(0, PHP_INT_MAX);
    $news_block = new \stdClass();
    $variables['news_id'] = 'news-wrapper-' . $rand_id;
    $block = $variables['content']['#block_content'];

    if ($block->field_heading->value) {
      $news_block->header = new \stdClass;
      $news_block->header->text = $block->field_heading->value;
    }
    if ($block->field_heading_text_color->value) {
      if (empty($news_block->header)) {
        $news_block->header = new \stdClass;
      }
      $news_block->header->color = $block->field_heading_text_color->value;
    }
    if ($block->field_news_link && $block->field_news_link->title && $block->field_news_link->uri) {
      $news_block->ctaButton = new \stdClass;
      $news_block->ctaButton->text = $block->field_news_link->title;
      $link = Url::fromUri($block->field_news_link->uri);
      $news_block->ctaButton->url = $link->toString();
    }
    if ($block->field_header_cta_color->value) {
      if (empty($news_block->ctaButton)) {
        $news_block->ctaButton = new \stdClass;
      }
      $news_block->ctaButton->color = $block->field_header_cta_color->value;
    }
    if ($block->field_card_cta_color->value) {
      $news_block->cardButton = new \stdClass;
      $news_block->cardButton->color = $block->field_card_cta_color->value;
    }
    if ($block->field_news_items_to_display->value) {
      $news_block->maxItems = $block->field_news_items_to_display->value;
    }
    if ($block->field_display->value) {
      $news_block->display = $block->field_display->value;
    }

    $news_block->dataSource = new \stdClass;

    $news_block->dataSource->url = '/asu-news-feed/';
    if ($block->field_feed_taxonomy_term->value) {
      // Allow only alphanumeric characters and underscore.
      $news_block->dataSource->url .= preg_replace('/[^A-Za-z0-9\_]/', '', $block->field_feed_taxonomy_term->value);
    }
    if ($block->field_news_feed_filter->value) {
      $news_block->dataSource->filters = $block->field_news_feed_filter->value;
    }

    $settings = [];
    $settings['components']['asu_news'][$rand_id] = $news_block;

    $variables['content']['#attached']['drupalSettings']['asu'] = $settings;
    $variables['content']['#attached']['library'][] = 'asu_news/news-component';

  }
}

/**
 * Implements hook_config_readonly_whitelist_patterns();
 * Make all the config files from this module readonly.
 * @return array
 */
function asu_news_config_readonly_whitelist_patterns() {
  // Get all the module configuration files.
  $module = \Drupal::service('module_handler')
    ->getModule(basename(__FILE__, '.module'))
    ->getName();
  $configs = \Drupal::service('webspark.config_manager')->getModuleConfigFiles($module);
  // Lock all the configurations from this module.
  if (\Drupal::state()->get('configuration_locked', TRUE)) {
    return array_map(function ($item) { return '~' . $item; }, $configs);
  }
  else {
    return [];
  }
}
