services:
  asu_config.config_manager:
    class: Drupal\asu_config_utility\ASUConfigUtilityConfigManager
    arguments: [ '@entity_type.manager', '@config.storage', '@config_update.extension_storage', '@config_update.config_update', '@module_handler', '@config.factory' ]
